sudo: false
dist: trusty
language: "node_js"
node_js:
  - "8"
# scripts that Travis must run on the build process
install:
  - npm install
  - npm run generate
# commits that travis should look into
git:
  depth: 10
# safelist
branches:
  only:
  - master
# cached modules folder
cache:
  directories:
    - "node_modules"
# packages pre-installed on travis VM
addons:
  apt:
    packages:
    - lftp
    - ncftp
# script deployment to ftp remote server
after_success:
  - ncftpput -R -v -u $FTP_USER -p $FTP_PASSWORD $FTP_HOST $FTP_PATH dist/*
#  - cd dist/
#  - pwd
#  - lftp -d -c "set ftp:ssl-allow off; open -d --user $FTP_USER --password $FTP_PASSWORD ftp://$FTP_HOST:21; mirror -R . $FTP_PATH"
#  - wput dist/ -up ftp://$FTP_USER:$FTP_PASSWORD@$FTP_HOST$FTP_PATH